Petroleance/Models/FanModels/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Petroleance.Models.FanModels
{
    public class Album
    {
        public int AlbumId { get; set; }
        public string Name { get; set; }

        public int? SImageId { get; set; }
        public virtual SystemImage SImage { get; set; }

        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        public virtual List<Image> Images { get; set; }
    }
}

Petroleance/Controllers/FanAdmin/AlbumsController.cs
using Microsoft.AspNet.Identity;
using Petroleance.Models;
using Petroleance.Models.FanModels;
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FanArt.Web.HtmlHelper;

namespace Petroleance.Controllers.FanAdmin
{
    [Authorize(Roles = "Administrator")]
    public class AlbumsController : Controller
    {
        // GET: Albums
        private ApplicationDbContext db = new ApplicationDbContext();


        public ActionResult Index()
        {
            string id = User.Identity.GetUserId();
            var albums = db.Albums;
            return View(albums.ToList().Where(a => a.UserId == id));
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            return RedirectToAction("ImageList", "Image", new { Id = id });
        }

        // GET: Albums/Create
        public ActionResult Create(string userid)
        {
            ViewBag.SImageId = new SelectList(db.SImages, "Id", "Name");
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            return View(userid);
        }

        // POST: Albums/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AlbumId,Name,SImageId")] Album album)
        {
            if (ModelState.IsValid)
            {
                album.UserId = User.Identity.GetUserId();
                db.Albums.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SImageId = new SelectList(db.SImages, "Id", "Name", album.SImageId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", album.UserId);
            return View(album);
        }

        // GET: Albums/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.SImageId = new SelectList(db.SImages, "Id", "Name", album.SImageId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", album.UserId);
            return View(album);
        }

        // POST: Albums/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AlbumId,Name")] Album album)
        {
            var albu = (from m in db.Albums where m.AlbumId == album.AlbumId select m).First();
            if (ModelState.IsValid)
            {
                albu.Name = album.Name;
                db.Entry(albu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SImageId = new SelectList(db.SImages, "Id", "Name", album.SImageId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", album.UserId);
            return View(album);
        }

        // GET: Albums/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Album album = db.Albums.Find(id);

            SystemImage image = db.SImages.Find(album.SImageId);
            string dd = image.Date.ToString().Replace(".", "-").Replace(" ", "-").Replace(":", "-");
            string u = User.Identity.Name;
            string DelFolderPath = FileHelper.GetSysImagePath(u, dd);
            FileHelper.DeleteFolder(DelFolderPath);
            db.SImages.Remove(image);

            db.Albums.Remove(album);
            db.SaveChanges();


            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Petroleance/Views/Albums/Create.cshtml
@model Petroleance.Models.FanModels.Album
@{
    ViewBag.Title = "Create";
     Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<article class="container">
    <h2>Create</h2>
    <div class="row">
        <div class="col l12">
            <div class="col s12 l12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Album</h4>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group hide">
                            @Html.LabelFor(model => model.SImage, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.SImageId, new { htmlAttributes = new { @class = "form-control", @id = "imageid" } })
                                @Html.ValidationMessageFor(model => model.SImageId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input id="create" type="submit" value="Create" class="btn disabled" disabled/>
                            </div>
                        </div>
                    </div>
                }
            </div>

            <div class="col s12 l12">
                <div class="row">
                    <form id="fileinfo" enctype="multipart/form-data" method="post" name="fileinfo">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <h5>Добавить изображение</h5>
                                <div class="row">
                                    <div class="col l2">
                                        <span class="btn fileinput-button" id="add-btn">
                                            <i class="glyphicon glyphicon-plus"></i>
                                            <span>Add files...</span>
                                            <input type="file" name="file" id="file" onchange="imgchange(this)">
                                        </span>
                                    </div>
                                    <div class="col l2">
                                        <a class="btn hide" href="#" id="start-upload">Обрезать</a>
                                        <br />
                                    </div>
                                </div>
                                <br />
                                <div class="row hide">
                                    <label>X1 <input type="text" size="4" id="x" name="x"></label>
                                    <label>Y1 <input type="text" size="4" id="y" name="y"></label>
                                    <label>W <input type="text" size="4" id="w" name="w"></label>
                                    <label>H <input type="text" size="4" id="h" name="h"></label>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>

                <div class="col s12">
                    <img class="responsive-img" id="uploaded-image" />
                </div>
            </div>

        </div>

        <br />
        <div class="col s12">
            <img class="responsive-img" id="crop-image" />
        </div>

        <div>
            @Html.ActionLink("Назад", "Index")
        </div>
    </div>

</article>



@section scripts{
    <script>
    var jqXHRData;
    var imageId;
    var upload = false;

    function imgchange(f) {
        var filePath = $('#file').val();
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#uploaded-image').attr('src', e.target.result);
            $("#start-upload").removeClass("hide");
            initCrop();
        };
        reader.readAsDataURL(f.files[0]);
    }

    function initCrop() {
        $(function () {
            $('#uploaded-image').Jcrop({
                setSelect: [0, 0, 150, 100],
                onChange: showCoords,
                onSelect: showCoords,
                aspectRatio: 16 / 9
            });
        });
    }

    $("#start-upload").on('click', function () {
        if (upload == false) {
            if (jqXHRData) {
                jqXHRData.submit();
            }
            return false;
        }
    });

    function destroyCrop() {
        var jcropApi = $('#uploaded-image').data('Jcrop');

        if (jcropApi !== undefined) {
            jcropApi.destroy();
            $('#uploaded-image').attr('style', "").attr("src", "");
        }
    }
    var ww;
    var hh;
    $('#uploaded-image').on('load', function () {
        var oheight = this.naturalHeight,
            owidth = this.naturalWidth;
        var rheight = this.clientHeight,
            rwidth = this.clientWidth;

        hh = oheight / rheight;
        ww = owidth / rwidth;

    });

    function showCoords(c) {
        $('#x').val(Math.floor(c.x * ww));
        $('#y').val(Math.floor(c.y * hh));
        $('#w').val(Math.floor(c.w * ww));
        $('#h').val(Math.floor(c.h * hh));
    };
    $(document).ready(function () {

        'use strict';
        var name = "Bekarys"
        $('#fileinfo').fileupload({
            url: '/Image/SystemImageCreate',
            dataType: 'json',
            add: function (e, data) {
                jqXHRData = data;
            },
            done: function (event, data) {
                if (data.result.isUploaded) {
                    destroyCrop();
                    $("#uploaded-image").attr("src", data.result.SendFilePath);
                    $("#add-btn").addClass("hide");
                    $("#create").removeClass('disabled');
                    $("#start-upload").addClass("disabled");
                    $("#create").attr('disabled', false);
                    $("#start-upload").attr('disabled', true);
                    $("#imageid").val(data.result._id);
                    upload = true;
                } else {

                }
            },
            fail: function (event, data) {
                if (data.files[0].error) {
                    alert(data.files[0].error);
                }
            }
        });
    });
</script>
    }

Petroleance/Views/Albums/Delete.cshtml
@model Petroleance.Models.FanModels.Album
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<article class="container">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Album</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.SImage.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SImage.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.User.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

</article>

Petroleance/Views/Albums/Details.cshtml
@model Petroleance.Models.FanModels.Album
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<article class="container">
    <h2>Details</h2>

    <div>
        <h4>Album</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.SImage.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SImage.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.User.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.AlbumId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</article>

Petroleance/Views/Albums/Edit.cshtml
@model Petroleance.Models.FanModels.Album
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<article class="container">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Album</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.AlbumId)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SImageId, "SImageId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SImageId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SImageId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</article>

Petroleance/Views/Albums/Index.cshtml
@model IEnumerable<Petroleance.Models.FanModels.Album>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<article class="container">
    <div class="col l12">
        <div class="row">
            <div class="panel-title">
                <h2>Албомы</h2>
                <br />
                <p>
                    @Html.ActionLink("Создать новый Альбом", "Create")
                </p>
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col s12 m4">
                    <div class="card">
                        <a href="@Url.Action("Details", "Albums", new { id=item.AlbumId })" class="col-sm-12 thumbnail text-center">
                            <div class="card-image">
                                <img alt="@item.SImage.Alt" class="responsive-img" src="@Url.Content(item.SImage.FilePath +"/"+item.SImage.Name + "small" + item.SImage.Extension)">
                                <span class="card-title black-text">@item.Name</span>
                            </div>
                        </a>
                        <div class="card-action">
                            <a href="@Url.Action("Edit", "Albums", new { id = item.AlbumId })">Редактировать</a>
                            <a href="@Url.Action("Delete", "Albums", new { id = item.AlbumId })">Удалить</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</article>